### ISSUE TITLE
Multi threading Simulation causes Exception

### ISSUE THREAD

**Issue by bohl-itemis** [Yakindu/statecharts#122]
Start a few statechart models as simulation. "Terminate & Relaunch" all simultaneous.
A few times repeating is maybe necessary to provoke the exeception.

A run with 2 statechart models:

![image](https://cloud.githubusercontent.com/assets/12081541/9174260/0d99dce0-3f7f-11e5-8f68-57ee272c5763.png)

java.util.ConcurrentModificationException
    at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:953)
    at java.util.LinkedList$ListItr.next(LinkedList.java:886)
    at org.eclipse.xtext.xbase.lib.IteratorExtensions.head(IteratorExtensions.java:140)
    at org.eclipse.xtext.xbase.lib.IterableExtensions.head(IterableExtensions.java:119)
    at org.yakindu.sct.simulation.core.sexec.interpreter.DefaultExecutionFlowInterpreter.run(DefaultExecutionFlowInterpreter.java:231)
    at org.yakindu.sct.simulation.core.sexec.interpreter.DefaultExecutionFlowInterpreter.scheduleAndRun(DefaultExecutionFlowInterpreter.java:225)
    at org.yakindu.sct.simulation.core.sexec.interpreter.DefaultExecutionFlowInterpreter.initialize(DefaultExecutionFlowInterpreter.java:123)
    at org.yakindu.sct.simulation.core.sexec.container.AbstractExecutionFlowSimulationEngine.init(AbstractExecutionFlowSimulationEngine.java:113)
    at org.yakindu.sct.simulation.core.debugmodel.SCTDebugTarget.init(SCTDebugTarget.java:77)
    at org.yakindu.sct.simulation.core.launch.AbstractSCTLaunchConfigurationDelegate.launch(AbstractSCTLaunchConfigurationDelegate.java:47)
    at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
    at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
    at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
    at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Exception in thread "Timer-8" java.lang.NullPointerException
    at org.yakindu.sct.simulation.core.sexec.interpreter.DefaultExecutionFlowInterpreter._execute(DefaultExecutionFlowInterpreter.java:331)
    at org.yakindu.sct.simulation.core.sexec.interpreter.DefaultExecutionFlowInterpreter.execute(DefaultExecutionFlowInterpreter.java:512)
    at org.yakindu.sct.simulation.core.sexec.interpreter.DefaultExecutionFlowInterpreter.run(DefaultExecutionFlowInterpreter.java:233)
    at org.yakindu.sct.simulation.core.sexec.interpreter.DefaultExecutionFlowInterpreter.scheduleAndRun(DefaultExecutionFlowInterpreter.java:225)
    at org.yakindu.sct.simulation.core.sexec.interpreter.DefaultExecutionFlowInterpreter.runCycle(DefaultExecutionFlowInterpreter.java:195)
    at org.yakindu.sct.simulation.core.sexec.container.AbstractExecutionFlowSimulationEngine.runCycle(AbstractExecutionFlowSimulationEngine.java:65)
    at org.yakindu.sct.simulation.core.sexec.container.CycleBasedSimulationEngine$1.run(CycleBasedSimulationEngine.java:41)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)

another run with 4 statechart models:

![image](https://cloud.githubusercontent.com/assets/12081541/9174313/5b7d0c48-3f7f-11e5-821e-42a4f1530658.png)

!ENTRY org.eclipse.core.jobs 4 2 2015-08-10 16:45:25.081
!MESSAGE An internal error occurred during: "Launching HistoryWithExitPoint.sct".
!STACK 0
java.lang.ClassCastException: org.yakindu.sct.model.sexec.impl.ExecutionStateImpl cannot be cast to org.yakindu.sct.model.sexec.ExecutionFlow
    at org.yakindu.sct.model.sexec.transformation.ReactionBuilder.defineCycle(ReactionBuilder.java:396)
    at org.yakindu.sct.model.sexec.transformation.ReactionBuilder$4.apply(ReactionBuilder.java:142)
    at org.yakindu.sct.model.sexec.transformation.ReactionBuilder$4.apply(ReactionBuilder.java:1)
    at org.eclipse.xtext.xbase.lib.IteratorExtensions.forEach(IteratorExtensions.java:363)
    at org.eclipse.xtext.xbase.lib.IterableExtensions.forEach(IterableExtensions.java:333)
    at org.yakindu.sct.model.sexec.transformation.ReactionBuilder.defineRegularStateReactions(ReactionBuilder.java:145)
    at org.yakindu.sct.model.sexec.transformation.ModelSequencer.transform(ModelSequencer.java:112)
    at org.yakindu.sct.simulation.core.sexec.container.AbstractExecutionFlowSimulationEngine.init(AbstractExecutionFlowSimulationEngine.java:98)
    at org.yakindu.sct.simulation.core.debugmodel.SCTDebugTarget.init(SCTDebugTarget.java:77)
    at org.yakindu.sct.simulation.core.launch.AbstractSCTLaunchConfigurationDelegate.launch(AbstractSCTLaunchConfigurationDelegate.java:47)
    at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
    at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
    at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
    at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by andreasmuelder** [comment]
Can not be reproduced
