### ISSUE TITLE
INVALID_CHARACTER_ERR on opening light_switch_series models

### ISSUE THREAD

**Issue by svenjawendler** [Yakindu/statecharts#1816]
How to reproduce: Close all editors, open new example -> light_switch_series -> directly open the model files (fast)
After a while working within the editor it is no problem to open the models.

Stack Trace:
org.w3c.dom.DOMException: INVALID_CHARACTER_ERR: Ungültiges XML-Zeichen angegeben. 
    at com.sun.org.apache.xerces.internal.dom.CoreDocumentImpl.createAttribute(Unknown Source)
    at com.sun.org.apache.xerces.internal.dom.ElementImpl.setAttribute(Unknown Source)
    at org.eclipse.ui.XMLMemento.putBoolean(XMLMemento.java:570)
    at org.yakindu.sct.ui.editor.partitioning.DiagramPartitioningEditor.rememberExpandState(DiagramPartitioningEditor.java:170)
    at org.yakindu.sct.ui.editor.partitioning.DiagramPartitioningEditor.restoreSashWidths(DiagramPartitioningEditor.java:158)
    at org.yakindu.sct.ui.editor.editor.StatechartDiagramEditor.createPartControl(StatechartDiagramEditor.java:527)
    at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:151)
    at org.eclipse.ui.internal.e4.compatibility.CompatibilityEditor.createPartControl(CompatibilityEditor.java:99)
    at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:355)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
    at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:990)
    at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:955)
    at org.eclipse.e4.core.internal.di.InjectorImpl.inject(InjectorImpl.java:124)
    at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:399)
    at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:318)
    at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:162)
    at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:105)
    at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:74)
    at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:56)
    at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:129)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:992)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:661)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:767)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:738)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:732)
    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:716)
    at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$1.handleEvent(PartServiceImpl.java:104)
    at org.eclipse.e4.ui.services.internal.events.UIEventHandler$1.run(UIEventHandler.java:40)
    at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:233)
    at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:144)
    at org.eclipse.swt.widgets.Display.syncExec(Display.java:4889)
    at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:212)
    at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:36)
    at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:201)
    at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:197)
    at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
    at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
    at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:135)
    at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:78)
    at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:39)
    at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:52)
    at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:60)
    at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:374)
    at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:173)
    at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:620)

    at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:584)

    at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:769)

    at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.bringToTop(PartServiceImpl.java:401)

    at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1188)

    at org.eclipse.ui.internal.WorkbenchPage.busyOpenEditor(WorkbenchPage.java:3261)

    at org.eclipse.ui.internal.WorkbenchPage.access$25(WorkbenchPage.java:3176)

    at org.eclipse.ui.internal.WorkbenchPage$10.run(WorkbenchPage.java:3158)

    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)

    at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3153)

    at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3117)

    at org.eclipse.ui.internal.WorkbenchPage.openEditor(WorkbenchPage.java:3107)

    at org.eclipse.ui.ide.IDE.openEditor(IDE.java:563)

    at org.eclipse.ui.ide.IDE.openEditor(IDE.java:518)

    at org.eclipse.jdt.internal.ui.javaeditor.EditorUtility.openInEditor(EditorUtility.java:360)

    at org.eclipse.jdt.internal.ui.javaeditor.EditorUtility.openInEditor(EditorUtility.java:167)

    at org.eclipse.jdt.ui.actions.OpenAction.run(OpenAction.java:279)

    at org.eclipse.jdt.ui.actions.OpenAction.run(OpenAction.java:244)

    at org.eclipse.jdt.ui.actions.SelectionDispatchAction.dispatchRun(SelectionDispatchAction.java:271)

    at org.eclipse.jdt.ui.actions.SelectionDispatchAction.run(SelectionDispatchAction.java:249)

    at org.eclipse.jdt.internal.ui.navigator.OpenAndExpand.run(OpenAndExpand.java:50)

    at org.eclipse.ui.actions.RetargetAction.run(RetargetAction.java:216)

    at org.eclipse.ui.navigator.CommonNavigatorManager$2.open(CommonNavigatorManager.java:191)

    at org.eclipse.ui.OpenAndLinkWithEditorHelper$InternalListener.open(OpenAndLinkWithEditorHelper.java:46)

    at org.eclipse.jface.viewers.StructuredViewer$2.run(StructuredViewer.java:851)

    at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)

    at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)

    at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)

    at org.eclipse.jface.viewers.StructuredViewer.fireOpen(StructuredViewer.java:848)

    at org.eclipse.jface.viewers.StructuredViewer.handleOpen(StructuredViewer.java:1163)

    at org.eclipse.ui.navigator.CommonViewer.handleOpen(CommonViewer.java:451)

    at org.eclipse.jface.util.OpenStrategy.fireOpenEvent(OpenStrategy.java:273)

    at org.eclipse.jface.util.OpenStrategy.access$2(OpenStrategy.java:268)

    at org.eclipse.jface.util.OpenStrategy$1.handleEvent(OpenStrategy.java:308)

    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)

    at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)

    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)

    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)

    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)

    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)

    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)

    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)

    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)

    at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)

    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)

    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)

    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)

    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)

    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)

    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)

    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)

    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)

    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)

    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

    at java.lang.reflect.Method.invoke(Unknown Source)

    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)

    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)

    at org.eclipse.equinox.launcher.Main.run(Main.java:1499)

**Comment by svenjawendler** [comment]
Cannot be reproduced with build from 14.12.2017 16:25:43.
