### ISSUE TITLE
find references exceptions

### ISSUE THREAD

**Issue by tangele** [Yakindu/statecharts#2239]
Version: 3.4.0 YAKINDU Statechart Tools Professional Edition

1. definition section contains only 'interface' keyword
    * right click in definition section -> find references -> exception

```
Could not find resource for selection!
Could not find resource for selection!
  java.lang.Thread.getStackTrace(Unknown Source)
  com.yakindu.sct.search.ui.handler.ModelReferenceHandler.execute(ModelReferenceHandler.java:39)
  org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
  org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
  sun.reflect.GeneratedMethodAccessor126.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
  org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
  org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
  org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
  org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
  org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
  org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
  org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
  org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:431)
  org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:446)
  org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:472)
  org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
  org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
  org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
  org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
  org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
  org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
  org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
  org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
  org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
  org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
  org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
  org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
  org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
  org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
  org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
  org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
  org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
  org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
  org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
  org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
  org.eclipse.equinox.launcher.Main.run(Main.java:1499)
```

2.  definition section contains: 
```
interface:
in event test
```

-> place cursor inside word 'interface' -> right click -> find references -> NullPointerException

```
java.lang.NullPointerException
	at org.eclipse.jface.viewers.StyledString.append(StyledString.java:281)
	at com.yakindu.sct.search.ui.provider.ResultColumnLabelProvider$1.getStyledText(ResultColumnLabelProvider.java:165)
	at org.eclipse.jface.viewers.DelegatingStyledCellLabelProvider.getStyledText(DelegatingStyledCellLabelProvider.java:206)
	at org.eclipse.jface.viewers.DelegatingStyledCellLabelProvider.update(DelegatingStyledCellLabelProvider.java:106)
	at org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerColumn.java:141)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:946)
	at org.eclipse.jface.viewers.AbstractTreeViewer$UpdateItemSafeRunnable.run(AbstractTreeViewer.java:117)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:1025)
	at org.eclipse.jface.viewers.StructuredViewer$UpdateItemSafeRunnable.run(StructuredViewer.java:475)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.StructuredViewer.updateItem(StructuredViewer.java:2159)
	at org.eclipse.jface.viewers.TreeViewer.replace(TreeViewer.java:472)
	at com.yakindu.sct.search.ui.provider.ModelSearchContentProvider.updateElement(ModelSearchContentProvider.java:159)
	at org.eclipse.jface.viewers.TreeViewer.virtualLazyUpdateWidget(TreeViewer.java:983)
	at org.eclipse.jface.viewers.TreeViewer.lambda$1(TreeViewer.java:255)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1103)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1088)
	at org.eclipse.swt.widgets.Tree.checkData(Tree.java:1661)
	at org.eclipse.swt.widgets.Tree.checkData(Tree.java:1640)
	at org.eclipse.swt.widgets.TreeItem.getText(TreeItem.java:918)
	at org.eclipse.jface.viewers.TreeViewerRow.getText(TreeViewerRow.java:88)
	at org.eclipse.jface.viewers.ViewerCell.getText(ViewerCell.java:111)
	at org.eclipse.jface.viewers.DelegatingStyledCellLabelProvider.update(DelegatingStyledCellLabelProvider.java:114)
	at org.eclipse.jface.viewers.ViewerColumn.refresh(ViewerColumn.java:141)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:946)
	at org.eclipse.jface.viewers.AbstractTreeViewer$UpdateItemSafeRunnable.run(AbstractTreeViewer.java:117)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.AbstractTreeViewer.doUpdateItem(AbstractTreeViewer.java:1025)
	at org.eclipse.jface.viewers.StructuredViewer$UpdateItemSafeRunnable.run(StructuredViewer.java:475)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.viewers.StructuredViewer.updateItem(StructuredViewer.java:2159)
	at org.eclipse.jface.viewers.TreeViewer.replace(TreeViewer.java:472)
	at com.yakindu.sct.search.ui.provider.ModelSearchContentProvider.updateElement(ModelSearchContentProvider.java:159)
	at org.eclipse.jface.viewers.TreeViewer.virtualLazyUpdateWidget(TreeViewer.java:983)
	at org.eclipse.jface.viewers.TreeViewer.createChildren(TreeViewer.java:587)
	at org.eclipse.jface.viewers.AbstractTreeViewer.createChildren(AbstractTreeViewer.java:763)
	at org.eclipse.jface.viewers.AbstractTreeViewer.internalExpand(AbstractTreeViewer.java:1624)
	at org.eclipse.jface.viewers.AbstractTreeViewer.expandToLevel(AbstractTreeViewer.java:1065)
	at com.yakindu.sct.search.ui.UIModelSearchResultPage$4.run(UIModelSearchResultPage.java:195)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:37)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4213)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3820)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
```

3. place the cursor in the definition section before the '@' of  `@EventDriven`. --> right click -> find references

```
Could not find model element for selection!
Could not find model element for selection!
  java.lang.Thread.getStackTrace(Unknown Source)
  com.yakindu.sct.search.ui.handler.ModelReferenceHandler.execute(ModelReferenceHandler.java:39)
  org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
  org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
  sun.reflect.GeneratedMethodAccessor126.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
  org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
  org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
  org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
  org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
  org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
  org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
  org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
  org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:431)
  org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:446)
  org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:472)
  org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
  org.eclipse.swt.widgets.Display.sendEvent(Display.java:4428)
  org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
  org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4238)
  org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3817)
  org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
  org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
  org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
  org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
  org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
  org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
  org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
  org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
  org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
  org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
  org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
  org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
  org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
  org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
  org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
  org.eclipse.equinox.launcher.Main.run(Main.java:1499)
```

**Comment by rherrmannr** [comment]
This is an pro issue
