### ISSUE TITLE
Image generator produces NPE

### ISSUE THREAD

**Issue by rherrmannr** [Yakindu/statecharts#2259]
See testplan: 17.1 - 17.3

NPE in Product
```
java.lang.NullPointerException
	at java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:106)
	at com.yakindu.sct.generator.image.ImageGenerator.generate(ImageGenerator.java:69)
	at org.yakindu.sct.generator.core.execution.SGraphGeneratorEntryExecutor.execute(SGraphGeneratorEntryExecutor.java:32)
	at org.yakindu.sct.generator.core.execution.AbstractGeneratorEntryExecutor.execute(AbstractGeneratorEntryExecutor.java:64)
	at org.yakindu.sct.generator.core.execution.GeneratorExecutorLookup.execute(GeneratorExecutorLookup.java:57)
	at org.yakindu.sct.generator.builder.EclipseContextGeneratorExecutorLookup$1.run(EclipseContextGeneratorExecutorLookup.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

NPE in Runtime

```
!ENTRY org.eclipse.ui 4 4 2018-09-17 16:19:22.418
!MESSAGE To avoid deadlock while executing Display.syncExec() with argument: com.yakindu.sct.generator.image.ImageGenerator$1@15f39c8c, thread Worker-10 will interrupt UI thread.
!SUBENTRY 1 org.eclipse.ui 4 4 2018-09-17 16:19:22.418
!MESSAGE Worker-10 thread is an instance of Worker or owns an ILock
!STACK 0
java.lang.IllegalStateException: Call stack for thread Worker-10
	at sun.management.ThreadImpl.dumpThreads0(Native Method)
	at sun.management.ThreadImpl.getThreadInfo(ThreadImpl.java:448)
	at org.eclipse.ui.internal.UILockListener.reportInterruption(UILockListener.java:206)
	at org.eclipse.ui.internal.UILockListener.interruptUI(UILockListener.java:176)
	at org.eclipse.ui.internal.PendingSyncExec.waitUntilExecuted(PendingSyncExec.java:82)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:153)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:5535)
	at com.yakindu.sct.generator.image.ImageGenerator.renderImage(ImageGenerator.java:131)
	at com.yakindu.sct.generator.image.ImageGenerator.generate(ImageGenerator.java:68)
	at org.yakindu.sct.generator.core.execution.SGraphGeneratorEntryExecutor.execute(SGraphGeneratorEntryExecutor.java:32)
	at org.yakindu.sct.generator.core.execution.AbstractGeneratorEntryExecutor.execute(AbstractGeneratorEntryExecutor.java:64)
	at org.yakindu.sct.generator.core.execution.GeneratorExecutorLookup.execute(GeneratorExecutorLookup.java:57)
	at org.yakindu.sct.generator.builder.EclipseContextGeneratorExecutorLookup$1.run(EclipseContextGeneratorExecutorLookup.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```

**Comment by andreasmuelder** [comment]
please provide steps to reproduce

**Comment by rherrmannr** [comment]
Take the digital watch example and run the digital_watch_images.sgen as described in the testplan.

Problem: We currently do not support pdf. 
I will add a validation/remove pdf from the feature.
