### ISSUE TITLE
Unhandled event loop exception while simulation

### ISSUE THREAD

**Issue by rherrmannr** [Yakindu/statecharts#2989]
I've started a multi sm simulation and ran it in background.
The error log is gathering a lot of `Unhandled event loop exceptions`
![image](https://user-images.githubusercontent.com/25480651/74449218-8dcaa280-4e7c-11ea-9be7-a2de8f40f1d3.png)

```
org.eclipse.emf.common.util.BasicEList$BasicIndexOutOfBoundsException: index=10, size=10
	at org.eclipse.emf.common.util.BasicEList.get(BasicEList.java:346)
	at org.eclipse.xtext.nodemodel.util.NodeModelUtils.getNode(NodeModelUtils.java:152)
	at org.yakindu.sct.model.sgraph.resource.AbstractSCTResource.getID(AbstractSCTResource.java:228)
	at org.eclipse.emf.ecore.xmi.impl.XMLResourceImpl.getURIFragment(XMLResourceImpl.java:629)
	at org.yakindu.sct.model.sgraph.resource.AbstractSCTResource.getURIFragment(AbstractSCTResource.java:223)
	at org.eclipse.emf.ecore.util.EcoreUtil.getURI(EcoreUtil.java:3071)
	at org.yakindu.base.gmf.runtime.util.EditPartUtils.findEditPartForSemanticElement(EditPartUtils.java:37)
	at org.yakindu.base.gmf.runtime.util.EditPartUtils.findEditPartForSemanticElement(EditPartUtils.java:43)
	at org.yakindu.base.gmf.runtime.util.EditPartUtils.findEditPartForSemanticElement(EditPartUtils.java:43)
	at org.yakindu.base.gmf.runtime.util.EditPartUtils.findEditPartForSemanticElement(EditPartUtils.java:43)
	at org.yakindu.base.gmf.runtime.highlighting.HighlightingSupportAdapter.getEditPartForSemanticElement(HighlightingSupportAdapter.java:139)
	at org.yakindu.base.gmf.runtime.highlighting.HighlightingSupportAdapter.highlight(HighlightingSupportAdapter.java:223)
	at org.yakindu.base.gmf.runtime.highlighting.IHighlightingSupport$Highlight.execute(IHighlightingSupport.java:56)
	at org.yakindu.base.gmf.runtime.highlighting.HighlightingSupportAdapter$3.run(HighlightingSupportAdapter.java:266)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4910)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4432)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:660)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```

**Comment by andreasmuelder** [comment]
@rherrmannr can you provide the model for testing purpose?
