### ISSUE TITLE
Not possible to use more than 2 regions in orthogonal state and join them via Synchronization element

### ISSUE THREAD

**Issue by pavelpa** [Yakindu/statecharts#3145]
Use case:
1. Entry state
2. synchronization block (split)
3. orthogonal state with 3 regions, each having only one state
4. synchronization block (join)
5. Final state

Setup:
SCXML Domain
yakindu version: professional 3.5.12

with those three regions in orhogonal state I get the following error when generating scxml. With two regions, it works well.

Generating 'default.scxml' to 'TestSynchronizationBlock3Regions/src-gen' ...
java.lang.ClassCastException: org.yakindu.sct.model.sgraph.impl.RegionImpl cannot be cast to org.yakindu.sct.model.sgraph.Vertex
	at com.yakindu.sct.generator.scxml.modifications.SynchronizationModification$7.apply(SynchronizationModification.java:109)
	at com.yakindu.sct.generator.scxml.modifications.SynchronizationModification$7.apply(SynchronizationModification.java:1)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.reduce(IteratorExtensions.java:647)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.reduce(IterableExtensions.java:565)
	at com.yakindu.sct.generator.scxml.modifications.SynchronizationModification.createAnchestorTransition(SynchronizationModification.java:112)
	at com.yakindu.sct.generator.scxml.modifications.SynchronizationModification$3.accept(SynchronizationModification.java:75)
	at com.yakindu.sct.generator.scxml.modifications.SynchronizationModification$3.accept(SynchronizationModification.java:1)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.yakindu.sct.generator.scxml.modifications.SynchronizationModification.modify(SynchronizationModification.java:78)
	at com.yakindu.sct.generator.scxml.SCXMLModelModifications$1.accept(SCXMLModelModifications.java:42)
	at com.yakindu.sct.generator.scxml.SCXMLModelModifications$1.accept(SCXMLModelModifications.java:1)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at com.yakindu.sct.generator.scxml.SCXMLModelModifications.modifyInternal(SCXMLModelModifications.java:45)
	at com.yakindu.sct.generator.scxml.SCXMLModelModifications.modify(SCXMLModelModifications.java:53)
	at com.yakindu.sct.generator.scxml.SCXMLModelModifications.modify(SCXMLModelModifications.java:69)
	at com.yakindu.sct.generator.scxml.SCXMLGenerator.generate(SCXMLGenerator.java:79)
	at org.yakindu.sct.generator.core.execution.SGraphGeneratorEntryExecutor.execute(SGraphGeneratorEntryExecutor.java:32)
	at org.yakindu.sct.generator.core.execution.AbstractGeneratorEntryExecutor.execute(AbstractGeneratorEntryExecutor.java:64)
	at org.yakindu.sct.generator.core.execution.GeneratorExecutorLookup.execute(GeneratorExecutorLookup.java:57)
	at org.yakindu.sct.generator.builder.EclipseContextGeneratorExecutorLookup$1.run(EclipseContextGeneratorExecutorLookup.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
default done.

**Comment by andreasmuelder** [comment]
@pavelpa thanks for the report. I will move the issue to the internal repository where the SCXML Code generator is located.
