### ISSUE TITLE
Code generator must not execute if generator model is erroneous

### ISSUE THREAD

**Issue by RainerKlute** [Yakindu/statecharts#328]
The code generator must not execute if generator model is erroneous. If it does, a StackOverflowException is thrown:

`java.lang.StackOverflowError
	at org.eclipse.emf.ecore.resource.impl.URIMappingRegistryImpl$URIMapImpl.getURI(URIMappingRegistryImpl.java:162)
	at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.normalize(ExtensibleURIConverterImpl.java:410)
	at org.eclipse.xtext.resource.XtextResourceSet$1.normalize(XtextResourceSet.java:290)
	at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.normalize(ExtensibleURIConverterImpl.java:449)
	at org.eclipse.xtext.resource.XtextResourceSet$1.normalize(XtextResourceSet.java:290)
	at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.normalize(ExtensibleURIConverterImpl.java:449)
	at org.eclipse.xtext.resource.XtextResourceSet$1.normalize(XtextResourceSet.java:290)`
…

**Comment by andreasmuelder** [comment]
@RainerKlute I can't reproduce this can you attach an example please?

**Comment by RainerKlute** [comment]
Sorry, @andreasmuelder, I don't remember exactly how I got there. I think the SCTUnit language hasn't been generated yet or something.

**Comment by andreasmuelder** [comment]
reopen if it still exists
