### ISSUE TITLE
generating code with Tracing features enabled fails because of conflicting guice bindings

### ISSUE THREAD

**Issue by jdicks** [Yakindu/statecharts#462]
When generating code for a sgen including the Tracing feature an exception is thrown which reports conflicting bindings.

This is a regression dependent to #366 where guice was introduced for all generators.

### Sample sgen:
```
GeneratorModel for yakindu::c {

	statechart default {

		feature Outlet {
			targetProject = "test.c"
			targetFolder = "src-gen"
			libraryTargetFolder = "src"
		}
		feature Tracing {
			enterState = true
			exitState = true
		}
		
	}
}
```

### StackTrace:
```
com.google.inject.CreationException: Guice creation errors:
1) A binding to java.lang.Boolean annotated with @com.google.inject.name.Named(value=ADD_TRACES) was already configured at org.yakindu.sct.generator.c.CCodeGenerator$1.configure(CCodeGenerator.java:79).
  at org.yakindu.sct.domain.generic.modules.GenericSequencerModule.configure(GenericSequencerModule.java:41)
1 error
                at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:435)
                at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:154)
                at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
                at com.google.inject.Guice.createInjector(Guice.java:95)
                at com.google.inject.Guice.createInjector(Guice.java:72)
                at com.google.inject.Guice.createInjector(Guice.java:62)
                at org.yakindu.sct.domain.generic.extension.GenericDomainInjectorProvider.getGeneratorInjector(GenericDomainInjectorProvider.java:158)
                at org.yakindu.sct.generator.core.GeneratorExecutor.getGenerator(GeneratorExecutor.java:81)
                at org.yakindu.sct.generator.core.GeneratorExecutor.executeGenerator(GeneratorExecutor.java:63)
                at org.yakindu.sct.generator.core.GeneratorExecutor$1.run(GeneratorExecutor.java:50)
                at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54) 
```

**Comment by jdicks** [comment]
FYI @nyssen
