### ISSUE TITLE
CallHandling example, main() code needs to call sm.init() before sm.enter()

### ISSUE THREAD

**Issue by gjsjohnmurray** [Yakindu/statecharts#493]
Using SCT 2.5 and Eclipse Mars.1, running CallHandlingClient gives me this error:
Exception in thread "main" java.lang.IllegalStateException: The statemachine needs to be initialized first by calling the init() function.
	at org.yakindu.scr.callhandling.CallHandlingStatemachine.enter(CallHandlingStatemachine.java:92)
	at CallHandlingClient.main(CallHandlingClient.java:13)

**Comment by RainerKlute** [comment]
Will be fixed in the next release.
