### ISSUE TITLE
Compare: picture of model vanishes sometimes.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Yakindu/statecharts#59]
```
The picture of the model vanishes.

Original order:

1. Compare the attached statecharts (default / Copy of Default)
2. Elapse the menue tree to the very bottom (attached picture)
3a. Press the button at the red arrow  
4a. The pictures disapear both.

3b. Press the orange button
4b. The left picture disapear


Changed order:

1. Change the name of "copy..." to something like "z_copy..." (must be after 
"default"). This causes that the models are switched from left <-> right.
2. Elapse the menue tree to the very bottom (attached picture)
3. Press the button at the red arrow  
4. Everything works fine

3b. Press the orange button
4b. The pictures disapear both.



```

Original issue reported on code.google.com by `malkne...@gmail.com` on 14 Oct 2014 at 10:53

Attachments:
![lr](https://cloud.githubusercontent.com/assets/12081541/8671642/3eb02f7c-2a27-11e5-9f45-fe75df1e7142.png)
* [Copy of default.sct](https://storage.googleapis.com/google-code-attachments/yakindu/issue-59/comment-0/Copy of default.sct)
* [default.sct](https://storage.googleapis.com/google-code-attachments/yakindu/issue-59/comment-0/default.sct)

**Comment by bohl-itemis** [comment]
Doesn't work at all in Mars target:

java.lang.UnsupportedOperationException
	at org.eclipse.emf.compare.impl.DiffImpl.basicGetMatch(DiffImpl.java:254)
	at org.eclipse.emf.compare.impl.DiffImpl.getMatch(DiffImpl.java:240)
	at org.eclipse.emf.compare.diagram.ide.ui.internal.structuremergeviewer.filters.groups.extenders.DiagramDiffExtender.addChildren(DiagramDiffExtender.java:44)
	at org.eclipse.emf.compare.rcp.ui.internal.structuremergeviewer.groups.impl.BasicDifferenceGroupImpl.buildSubTree(BasicDifferenceGroupImpl.java:458)
	at org.eclipse.emf.compare.rcp.ui.internal.structuremergeviewer.groups.impl.BasicDifferenceGroupImpl.manageRefines(BasicDifferenceGroupImpl.java:439)
	at org.eclipse.emf.compare.rcp.ui.internal.structuremergeviewer.groups.impl.BasicDifferenceGroupImpl.buildSubTree(BasicDifferenceGroupImpl.java:353)
	at org.eclipse.emf.compare.rcp.ui.internal.structuremergeviewer.groups.impl.BasicDifferenceGroupImpl.buildSubTree(BasicDifferenceGroupImpl.java:305)
	at org.eclipse.emf.compare.rcp.ui.internal.structuremergeviewer.groups.impl.BasicDifferenceGroupImpl.buildMatchSubTrees(BasicDifferenceGroupImpl.java:589)
	at org.eclipse.emf.compare.rcp.ui.internal.structuremergeviewer.groups.impl.BasicDifferenceGroupImpl.buildSubTree(BasicDifferenceGroupImpl.java:580)
	at org.eclipse.emf.compare.rcp.ui.internal.structuremergeviewer.groups.impl.DefaultGroupProvider.buildGroups(DefaultGroupProvider.java:43)
	at org.eclipse.emf.compare.rcp.ui.structuremergeviewer.groups.AbstractDifferenceGroupProvider.getGroups(AbstractDifferenceGroupProvider.java:174)
	at org.eclipse.emf.compare.rcp.ui.internal.structuremergeviewer.groups.provider.TreeNodeItemProviderSpec.getChildren(TreeNodeItemProviderSpec.java:101)
	at org.eclipse.emf.edit.ui.provider.AdapterFactoryContentProvider.getChildren(AdapterFactoryContentProvider.java:175)
	at org.eclipse.emf.compare.ide.ui.internal.structuremergeviewer.EMFCompareStructureMergeViewerContentProvider.getChildren(EMFCompareStructureMergeViewerContentProvider.java:387)
	at org.eclipse.emf.compare.ide.ui.internal.structuremergeviewer.EMFCompareStructureMergeViewerContentProvider$EMFCompareStructureMergeViewerContentProviderDeferredAdapter.fetchDeferredChildren(EMFCompareStructureMergeViewerContentProvider.java:180)
	at org.eclipse.ui.progress.DeferredTreeContentManager$1.run(DeferredTreeContentManager.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY org.eclipse.core.jobs 4 2 2015-07-21 11:14:41.863
!MESSAGE An internal error occurred during: "Fetching children of the current comparison".
!STACK 0
java.lang.UnsupportedOperationException
	at org.eclipse.emf.compare.impl.DiffImpl.basicGetMatch(DiffImpl.java:254)
	at org.eclipse.emf.compare.impl.DiffImpl.getMatch(DiffImpl.java:240)
	at org.eclipse.emf.compare.diagram.ide.ui.internal.structuremergeviewer.filters.groups.extenders.DiagramDiffExtender.addChildren(DiagramDiffExtender.java:44)
	at org.eclipse.emf.compare.rcp.ui.internal.structuremergeviewer.groups.impl.BasicDifferenceGroupImpl.buildSubTree(BasicDifferenceGroupImpl.java:458)
	at org.eclipse.emf.compare.rcp.ui.internal.structuremergeviewer.groups.impl.BasicDifferenceGroupImpl.manageRefines(BasicDifferenceGroupImpl.java:439)
	at org.eclipse.emf.compare.rcp.ui.internal.structuremergeviewer.groups.impl.BasicDifferenceGroupImpl.buildSubTree(BasicDifferenceGroupImpl.java:353)
	at org.eclipse.emf.compare.rcp.ui.internal.structuremergeviewer.groups.impl.BasicDifferenceGroupImpl.buildSubTree(BasicDifferenceGroupImpl.java:305)
	at org.eclipse.emf.compare.rcp.ui.internal.structuremergeviewer.groups.impl.BasicDifferenceGroupImpl.buildMatchSubTrees(BasicDifferenceGroupImpl.java:589)
	at org.eclipse.emf.compare.rcp.ui.internal.structuremergeviewer.groups.impl.BasicDifferenceGroupImpl.buildSubTree(BasicDifferenceGroupImpl.java:580)
	at org.eclipse.emf.compare.rcp.ui.internal.structuremergeviewer.groups.impl.DefaultGroupProvider.buildGroups(DefaultGroupProvider.java:43)
	at org.eclipse.emf.compare.rcp.ui.structuremergeviewer.groups.AbstractDifferenceGroupProvider.getGroups(AbstractDifferenceGroupProvider.java:174)
	at org.eclipse.emf.compare.rcp.ui.internal.structuremergeviewer.groups.provider.TreeNodeItemProviderSpec.getChildren(TreeNodeItemProviderSpec.java:101)
	at org.eclipse.emf.edit.ui.provider.AdapterFactoryContentProvider.getChildren(AdapterFactoryContentProvider.java:175)
	at org.eclipse.emf.compare.ide.ui.internal.structuremergeviewer.EMFCompareStructureMergeViewerContentProvider.getChildren(EMFCompareStructureMergeViewerContentProvider.java:387)
	at org.eclipse.emf.compare.ide.ui.internal.structuremergeviewer.EMFCompareStructureMergeViewerContentProvider$EMFCompareStructureMergeViewerContentProviderDeferredAdapter.fetchDeferredChildren(EMFCompareStructureMergeViewerContentProvider.java:180)
	at org.eclipse.ui.progress.DeferredTreeContentManager$1.run(DeferredTreeContentManager.java:232)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by bohl-itemis** [comment]
default.sct: http://pastebin.com/iW86wXbj
Copy of default.sct: http://pastebin.com/DdVU83cM

**Comment by bohl-itemis** [comment]
problem was solved with new EMF compare release
