### ISSUE TITLE
NPE java generator

### ISSUE THREAD

**Issue by DominikTesch** [Yakindu/statecharts#738]
java.lang.NullPointerException
	at org.yakindu.sct.generator.java.features.EventBasedRunnableFeature.getNameSuffix(EventBasedRunnableFeature.java:67)
	at org.yakindu.sct.generator.java.features.EventBasedRunnableFeature.eventBasedWrapperClassName(EventBasedRunnableFeature.java:78)
	at org.yakindu.sct.generator.java.EventBasedRunnableWrapper.generateEventBasedRunnableWrapper(EventBasedRunnableWrapper.java:74)
	at org.yakindu.sct.generator.java.JavaGenerator.generate(JavaGenerator.java:128)
	at org.yakindu.sct.generator.java.JavaCodeGenerator.generate(JavaCodeGenerator.java:41)
	at org.yakindu.sct.generator.java.AbstractJavaCodeGenerator.runGenerator(AbstractJavaCodeGenerator.java:25)
	at org.yakindu.sct.generator.core.impl.AbstractSGraphModelGenerator.doGenerate(AbstractSGraphModel
get NPE by using "feature RunnableWrapper". 

Generator.java:111)
	at org.yakindu.sct.generator.core.impl.AbstractSGraphModelGenerator.generate(AbstractSGraphModelGenerator.java:81)
	at org.yakindu.sct.generator.core.GeneratorExecutor.executeGenerator(GeneratorExecutor.java:69)
	at org.yakindu.sct.generator.core.GeneratorExecutor$1.run(GeneratorExecutor.java:55)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by tkutz** [comment]
Fixed with pull request #739.
